### ISSUE TITLE
Will it work on CPU machine? Thanks

### ISSUE THREAD

**Issue by aivyon** [camenduru/stable-diffusion-webui-offline#2]

**Comment by camenduru** [comment]
nope

**Comment by aivyon** [comment]
Hi [camenduru](https://github.com/camenduru),
just another question regarding the offline feature
I created the html page but it is still looking for all the external fonts and links
So what did you mean by offline?
thank you for sharing

**Comment by camenduru** [comment]
this repo for preparing please try this https://camenduru.itch.io/stable-diffusion-webui

**Comment by aivyon** [comment]
Hi [camenduru](https://github.com/camenduru)
thank you for your response!
So referring to https://camenduru.itch.io/stable-diffusion-webui:
"Stable Diffusion WebUI
Update: I am pushing new versions via [butler](https://itch.io/docs/butler) to itch.io server. You will get automatic patch updates if you are using the [itch app](https://itch.io/app)"

I go to https://itch.io/docs/butler/
and where I should download the stable-diffusion-webui-win.zip from?
should I go to https://github.com/itchio/itch ?
thank you!

**Comment by camenduru** [comment]
there is a download button

![Screenshot 2023-01-08 193828](https://user-images.githubusercontent.com/54370274/211208337-694fcfe3-4482-4985-ac6b-99a458d78725.jpg)

**Comment by aivyon** [comment]
Hi 
I ran the run.bat  of stable-diffusion-webui-win
but the html tha was generated is still pointing to all the external liks 
such as "https://gradio.app/" "https://fonts.googleapis.com"  "https://fonts.googleapis.com/css?family=Source Sans Pro"
https://fonts.googleapis.com/css?family=IBM Plex Mono"
="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.1/iframeResizer.contentWindow.min.js">

![image](https://user-images.githubusercontent.com/50579056/211252889-c4182d24-9082-4ef3-9862-5b614ae63cc9.png)

so it looks like it still won't run on the offline machine without internet connection
thank you
