### ISSUE TITLE
FastAPI Error?

### ISSUE THREAD

**Issue by SquidBoiMusic** [camenduru/stable-diffusion-webui-offline#3]
I followed the steps, and ran the Install.bat twice, but I keep getting this error.

Windows long-path support already enabled.
Traceback (most recent call last):
  File "C:\Stable Diffusion Webui Offline\stable-diffusion-webui\webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

I tried installing fastapi via pip, but it didn't fix the issue.
Does it need to be installed somewhere specific, or am I missing something? 🤔

**Comment by ZevveZ** [comment]
+1

**Comment by ZevveZ** [comment]
Modify the startup parameters of file "install.bat" according to your computer
 @CALL python -B launch.py ​​--you-need

For example, modify it to
@CALL python -B launch.py ​​--skip-torch-cuda-test --listen --use-cpu all --no-half --precision full --enable-insecure-extension-access

**Comment by RockonWeb** [comment]
> Modify the startup parameters of file "install.bat" according to your computer @call python -B launch.py ​​--you-need
> 
> For example, modify it to @call python -B launch.py ​​--skip-torch-cuda-test --listen --use-cpu all --no-half --precision full --enable-insecure-extension-access

Sorry, how i can do this? and where?
